name: Trigger Render Deploy

on:
  workflow_run:
    workflows:
      - "Build and Publish Docker Image"
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger webhook
        env:
          RENDER_KEY: ${{secrets.RENDER_KEY}}
        run: curl https://api.render.com/deploy/srv-cl8es8quuipc73eq490g?key=$RENDER_KEY
