name: Docker Image CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag phuochungus/homeland_php:prod
      - name: Publish the Docker image
        run: docker push phuochungus/homeland_php:prod
